Repository pixiv/charcoal, pull requests merged in 2023-09, with the labels that each got.

#378 fix: typo
  docs/src/pages/@charcoal-ui/react/Button/apiData.tsx
  docs/src/pages/@charcoal-ui/react/Button/sections.tsx
  docs/src/pages/@charcoal-ui/react/Button/sizes.tsx
  docs/src/pages/@charcoal-ui/react/Button/sizies.tsx
  docs/src/pages/@charcoal-ui/react/Modal/sections.tsx
  docs/src/pages/@charcoal-ui/react/TextArea/sections.tsx
  docs/src/pages/@charcoal-ui/react/TextField/sections.tsx
  docs/src/pages/@charcoal-ui/styled/borderRadius/index.page.tsx
  docs/src/pages/@charcoal-ui/styled/quickstart.page.tsx
  packages/icons-cli/src/generateSource.ts
  packages/icons/src/ssr.ts
  packages/react-sandbox/src/components/Carousel/index.tsx
  packages/react-sandbox/src/components/Filter/index.story.tsx
  packages/react-sandbox/src/components/Layout/index.tsx
  packages/react-sandbox/src/components/MenuListItem/index.story.tsx
  packages/react-sandbox/src/components/Pager/index.tsx
  packages/react-sandbox/src/foundation/constants.ts
  packages/react-sandbox/src/index.ts
  packages/react/src/components/Button/index.test.tsx
  packages/react/src/components/Button/index.tsx
  packages/react/src/components/Checkbox/performance.test.tsx
  packages/react/src/components/LoadingSpinner/index.tsx
  packages/styled/src/builders/colors.ts
  packages/styled/src/index.test.tsx
  packages/styled/src/index.ts
  packages/tailwind-config/src/gradient/plugin.ts
  packages/tailwind-diff/src/packageManager.ts
  packages/tailwind-diff/src/withPackages.ts
  pages/pages/utilities/styled.md
Labels: patch

#379 fix: add background to CharcoalProvider
  docs/yarn.lock
  packages/react/src/core/CharcoalProvider.tsx
Labels: patch

#382 upgrade storybook v7.4
  .github/workflows/test.yml
  .storybook/main.js
  package.json
  packages/icons/package.json
  packages/react-sandbox/package.json
  packages/react/package.json
  yarn.lock
Labels: dependencies, patch

#385 chore: comment out build-storybook-vite
  .github/workflows/test.yml
Labels: patch

#383 react-sandbox の Pager に要素の数を調節できるpropsの追加
  packages/react-sandbox/src/components/Pager/index.story.tsx
  packages/react-sandbox/src/components/Pager/index.tsx
Labels: minor

#391 wip: build-storybookが壊れているのを直す
  .github/workflows/gh-pages.yml
  .github/workflows/test.yml
Labels: patch

#392 feat: Checkboxコンポーネントのinvalid状態を実装
  packages/react/src/components/Checkbox/index.story.tsx
  packages/react/src/components/Checkbox/index.tsx
Labels: minor
