Repository pixiv/charcoal, pull requests merged in 2023-04, with the labels that each got.

#292 docs: ドキュメントを更新
  docs/src/components/NavList.tsx
  docs/src/pages/@charcoal-ui/react/Button/apiData.tsx
  docs/src/pages/@charcoal-ui/react/CharcoalProviderExample.tsx
  docs/src/pages/@charcoal-ui/react/Checkbox/apiData.tsx
  docs/src/pages/@charcoal-ui/react/DropdownSelector/apiData.tsx
  docs/src/pages/@charcoal-ui/react/Icon/apiData.tsx
  docs/src/pages/@charcoal-ui/react/IconButton/apiData.tsx
  docs/src/pages/@charcoal-ui/react/LoadingSpinner/apiData.tsx
  docs/src/pages/@charcoal-ui/react/Modal/apiData.tsx
  docs/src/pages/@charcoal-ui/react/MultiSelect/apiData.tsx
  docs/src/pages/@charcoal-ui/react/Radio/apiData.tsx
  docs/src/pages/@charcoal-ui/react/SegmentedControl/apiData.tsx
  docs/src/pages/@charcoal-ui/react/Switch/apiData.tsx
  docs/src/pages/@charcoal-ui/react/TagItem/apiData.tsx
  docs/src/pages/@charcoal-ui/react/TextField/apiData.tsx
  docs/src/pages/@charcoal-ui/react/_components/ApiTable.tsx
  docs/src/pages/@charcoal-ui/react/quickstart.page.tsx
  docs/src/pages/@charcoal-ui/styled/disabled/index.page.tsx
  docs/src/pages/@charcoal-ui/styled/height/index.page.tsx
  docs/yarn.lock
Labels: documentation

#290 PR に semver のラベルがついてなかったら CI を落とす
  .github/workflows/enforce-semver.yml
  .github/workflows/version.yml
Labels: minor

#297 v3.0.0: feat: fixed -> fullWidth
  docs/src/pages/@charcoal-ui/react/Button/apiData.tsx
  docs/src/pages/@charcoal-ui/react/Button/sections.tsx
  docs/yarn.lock
  packages/react/src/components/Button/index.story.tsx
  packages/react/src/components/Button/index.tsx
  packages/react/src/components/Modal/index.story.tsx
  packages/react/src/components/Modal/index.tsx
Labels: major

#261 v3.0.0: feat: dropdownSelectorを作り直す
  .github/workflows/docs-hosting-pr.yml
  docs/src/components/NavList.tsx
  docs/src/pages/@charcoal-ui/react/DropdownSelector/ExampleDropdownSelector.tsx
  docs/src/pages/@charcoal-ui/react/DropdownSelector/apiData.tsx
  docs/src/pages/@charcoal-ui/react/DropdownSelector/index.page.tsx
  docs/src/pages/@charcoal-ui/react/DropdownSelector/sections.tsx
  docs/src/pages/@charcoal-ui/react/_components/Previews.tsx
  docs/src/pages/v3.0.0-guide.page.tsx
  docs/yarn.lock
  packages/react/src/components/DropdownSelector/DropdownPopover.tsx
  packages/react/src/components/DropdownSelector/ListBoxSection.tsx
  packages/react/src/components/DropdownSelector/Listbox.tsx
  packages/react/src/components/DropdownSelector/Option.tsx
  packages/react/src/components/DropdownSelector/OptionItem.tsx
  packages/react/src/components/DropdownSelector/index.story.tsx
  packages/react/src/components/DropdownSelector/index.tsx
  packages/react/src/components/DropdownSelector/utils/focusIfHTMLLIElement.tsx
  packages/react/src/components/DropdownSelector/utils/handleFocusByKeyBoard.tsx
  packages/react/src/index.ts
  yarn.lock
Labels: major

#303 refactor: remove sample package
  package.json
  packages/sample/.babelrc
  packages/sample/.gitignore
  packages/sample/README.md
  packages/sample/env.d.ts
  packages/sample/next-env.d.ts
  packages/sample/next.config.js
  packages/sample/package.json
  packages/sample/pages/_app.tsx
  packages/sample/pages/_document.tsx
  packages/sample/pages/index.tsx
  packages/sample/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: patch
