Repository pixiv/charcoal, pull requests merged in 2023-06, with the labels that each got.

#322 fix: aria-label warning
  packages/react/src/components/SegmentedControl/index.tsx
Labels: patch

#323 test: buttonのスナップショットを追加
  packages/react/src/components/Button/__snapshots__/index.test.tsx.snap
  packages/react/src/components/Button/index.test.tsx
Labels: patch

#320 v3.0.0: DropdownSelectorの内部を更新 + etc
  docs/package.json
  docs/src/components/GlobalStyle.tsx
  docs/src/components/NavList.tsx
  docs/src/pages/@charcoal-ui/react/Checkbox/apiData.tsx
  docs/src/pages/@charcoal-ui/react/Checkbox/sections.tsx
  docs/src/pages/@charcoal-ui/react/DropdownSelector/ExampleDropdownSelector.tsx
  docs/src/pages/@charcoal-ui/react/DropdownSelector/apiData.tsx
  docs/src/pages/@charcoal-ui/react/DropdownSelector/index.page.tsx
  docs/src/pages/@charcoal-ui/react/DropdownSelector/sections.tsx
  docs/src/pages/@charcoal-ui/react/Icon/apiData.tsx
  docs/src/pages/v3.0.0-guide.page.tsx
  docs/yarn.lock
  packages/react/src/components/DropdownSelector/Divider.tsx
  packages/react/src/components/DropdownSelector/DropdownMenuItem.tsx
  packages/react/src/components/DropdownSelector/DropdownPopover.tsx
  packages/react/src/components/DropdownSelector/ListItem/index.story.tsx
  packages/react/src/components/DropdownSelector/ListItem/index.tsx
  packages/react/src/components/DropdownSelector/MenuItem/index.tsx
  packages/react/src/components/DropdownSelector/MenuItem/internals/handleFocusByKeyBoard.tsx
  packages/react/src/components/DropdownSelector/MenuItem/internals/useMenuItemHandleKeyDown.tsx
  packages/react/src/components/DropdownSelector/MenuItemGroup/index.tsx
  packages/react/src/components/DropdownSelector/MenuList/MenuListContext.ts
  packages/react/src/components/DropdownSelector/MenuList/index.story.tsx
  packages/react/src/components/DropdownSelector/MenuList/index.tsx
  packages/react/src/components/DropdownSelector/MenuList/internals/getValuesRecursive.tsx
  packages/react/src/components/DropdownSelector/OptionItem.tsx
  packages/react/src/components/DropdownSelector/Popover/index.story.tsx
  packages/react/src/components/DropdownSelector/Popover/index.tsx
  packages/react/src/components/DropdownSelector/index.story.tsx
  packages/react/src/components/DropdownSelector/index.tsx
  packages/react/src/components/DropdownSelector/utils/findPreviewRecursive.tsx
  packages/react/src/components/DropdownSelector/utils/focusIfHTMLLIElement.tsx
  packages/react/src/components/DropdownSelector/utils/handleFocusByKeyBoard.tsx
  packages/react/src/index.ts
Labels: major

#328 fix: requiredカラムの???を修正
  docs/src/pages/@charcoal-ui/react/_components/ApiTable.tsx
Labels: patch

#330 fix: npmjsバッジのラベルが @charcoal-ui/icons のままだったのを修正
  docs/src/pages/@charcoal-ui/tailwind-diff/quickstart.page.tsx
Labels: patch

#327 MultiSelect の props を更新
  docs/src/pages/@charcoal-ui/react/MultiSelect/ExampleMultiSelect.tsx
  docs/src/pages/@charcoal-ui/react/MultiSelect/apiData.tsx
  docs/src/pages/@charcoal-ui/react/MultiSelect/index.page.tsx
  docs/src/pages/@charcoal-ui/react/MultiSelect/sections.tsx
  docs/src/pages/v3.0.0-guide.page.tsx
  docs/yarn.lock
  packages/react/src/components/MultiSelect/context.ts
  packages/react/src/components/MultiSelect/index.story.tsx
  packages/react/src/components/MultiSelect/index.test.tsx
  packages/react/src/components/MultiSelect/index.tsx
Labels: major

#337 ドキュメントの修正と更新
  docs/src/pages/@charcoal-ui/react/_components/Previews.tsx
  docs/src/pages/v3.0.0-guide.page.tsx
Labels: patch

#339 fix: fix misleading `<Modal>` usage
  packages/react/src/components/Modal/index.tsx
Labels: patch

#325 Radio の props を更新
  docs/src/pages/@charcoal-ui/react/Radio/apiData.tsx
  docs/src/pages/@charcoal-ui/react/Radio/index.page.tsx
  docs/src/pages/@charcoal-ui/react/Radio/sections.tsx
  docs/src/pages/v3.0.0-guide.page.tsx
  docs/yarn.lock
  packages/react/src/components/Radio/index.story.tsx
  packages/react/src/components/Radio/index.test.tsx
  packages/react/src/components/Radio/index.tsx
  yarn.lock
Labels: major

#336 TextArea と TextField は通常のhtmlと同じ属性を受け付ける
  docs/src/pages/@charcoal-ui/react/TextArea/apiData.tsx
  docs/src/pages/@charcoal-ui/react/TextArea/index.page.tsx
  docs/src/pages/@charcoal-ui/react/TextField/apiData.tsx
  docs/yarn.lock
  packages/react/src/_lib/compat.ts
  packages/react/src/components/TextArea/index.tsx
  packages/react/src/components/TextField/index.tsx
Labels: major

#342 v3.0.0: usePopoverの副作用が出ないように修正
  docs/yarn.lock
  packages/react/src/components/DropdownSelector/index.tsx
Labels: patch

#338 ドキュメントのテーブルで???になるのを修正
  docs/src/components/Table.tsx
  docs/yarn.lock
Labels: patch

#343 chore(react): change icon color
  packages/react/src/components/TextField/index.story.tsx
Labels: patch

#291 Issue 263 すべてのコンポーネントを className と ref を受け取るようにする
  packages/react/src/components/Checkbox/index.story.tsx
  packages/react/src/components/Checkbox/index.tsx
  packages/react/src/components/LoadingSpinner/index.story.tsx
  packages/react/src/components/LoadingSpinner/index.tsx
  packages/react/src/components/Modal/index.tsx
  packages/react/src/components/MultiSelect/index.story.tsx
  packages/react/src/components/MultiSelect/index.tsx
  packages/react/src/components/Radio/index.story.tsx
  packages/react/src/components/Radio/index.tsx
  packages/react/src/components/SegmentedControl/index.tsx
  packages/react/src/components/Switch/index.tsx
Labels: minor

#346 refactor: reactのimportを削除
  packages/react/src/components/DropdownSelector/DropdownMenuItem.tsx
  packages/react/src/components/DropdownSelector/ListItem/index.story.tsx
  packages/react/src/components/DropdownSelector/ListItem/index.tsx
  packages/react/src/components/DropdownSelector/MenuItem/index.tsx
  packages/react/src/components/DropdownSelector/MenuItem/internals/useMenuItemHandleKeyDown.tsx
  packages/react/src/components/DropdownSelector/MenuItemGroup/index.tsx
  packages/react/src/components/DropdownSelector/MenuList/index.story.tsx
  packages/react/src/components/DropdownSelector/MenuList/index.tsx
  packages/react/src/components/DropdownSelector/MenuList/internals/getValuesRecursive.tsx
  packages/react/src/components/DropdownSelector/Popover/index.story.tsx
  packages/react/src/components/DropdownSelector/Popover/index.tsx
  packages/react/src/components/DropdownSelector/utils/findPreviewRecursive.tsx
  packages/react/src/components/TextArea/TextArea.story.tsx
  packages/react/src/components/TextArea/index.tsx
Labels: major

#347 v3.0.0: TextAreaのフォーカスアニメーションを修正
  packages/react/src/components/TextArea/index.tsx
  yarn.lock
Labels: patch

#348 docs: ariaLabel->labelの変更を追記
  docs/src/pages/v3.0.0-guide.page.tsx
Labels: patch
