Repository pixiv/charcoal, pull requests merged in 2023-05, with the labels that each got.

#304 feat: modalを開いてもスクロール可能に
  packages/react/src/components/Modal/index.tsx
Labels: minor

#299 fix: SegmentedControlにラベルの付与を追加
  packages/react/src/components/DropdownSelector/index.story.tsx
  packages/react/src/components/SegmentedControl/index.story.tsx
  packages/react/src/components/SegmentedControl/index.tsx
Labels: minor

#309 fix: fix LoadingSpinner style
  docs/src/pages/@charcoal-ui/react/LoadingSpinner/index.page.tsx
  docs/yarn.lock
  packages/react/src/components/LoadingSpinner/index.tsx
Labels: patch

#308 feat: 型のexportを追加
  packages/react/src/index.ts
Labels: minor

#302 @charcoal-ui/icons のドキュメントのページを追加
  docs/src/components/GlobalStyle.tsx
  docs/src/components/InlineCode.tsx
  docs/src/components/NavList.tsx
  docs/src/components/Table.tsx
  docs/src/pages/@charcoal-ui/icons/element.page.tsx
  docs/src/pages/@charcoal-ui/icons/extend.page.tsx
  docs/src/pages/@charcoal-ui/icons/quickstart.page.tsx
  docs/src/pages/@charcoal-ui/icons/react.page.tsx
  docs/src/pages/@charcoal-ui/icons/ssr.page.tsx
  docs/src/pages/@charcoal-ui/react/_components/ApiTable.tsx
  docs/src/pages/@charcoal-ui/react/ssr.page.tsx
  docs/src/utils/string.ts
Labels: minor

#312 fix: textFieldのprefixがinputの背景色の影響を受ける #248
  docs/src/pages/@charcoal-ui/react/TextField/sections.tsx
  packages/react/src/components/TextField/index.tsx
Labels: patch

#316 tailwind-diff のドキュメントを追加
  docs/src/components/NavList.tsx
  docs/src/pages/@charcoal-ui/tailwind-diff/check.page.tsx
  docs/src/pages/@charcoal-ui/tailwind-diff/dump.page.tsx
  docs/src/pages/@charcoal-ui/tailwind-diff/quickstart.page.tsx
Labels: documentation, minor

#315 styled: theme.border の色を CSS Variables で扱うようにする
  packages/styled/src/TokenInjector.tsx
  packages/styled/src/__snapshots__/index.test.tsx.snap
  packages/styled/src/builders/border.ts
  packages/styled/src/util.ts
Labels: major

#319 fix: <RadioInput> のラジオボタンも cursor: pointer となるように修正した
  packages/react/src/components/Radio/index.tsx
Labels: minor
