Repository pixiv/charcoal, pull requests merged in 2023-07, with the labels that each got.

#356 fix: remove `<Modal>` vertical padding
  packages/react/src/components/Modal/index.tsx
Labels: patch

#357 fix: update doc url for v3.0.0
  README.md
Labels: patch

#359 DropdownButtonに type=button をつける
  packages/react/src/components/DropdownSelector/index.story.tsx
  packages/react/src/components/DropdownSelector/index.tsx
Labels: patch

#358 fix: Modalの大きさによってスクロールバーが非表示になるように修正
  packages/react/src/components/Modal/index.tsx
Labels: patch

#360 yarn release from-package をするActions追加
  .github/workflows/publish.yml
Labels: github_actions, patch

#361 fix: add yes option to yarn lerna version
  .github/workflows/publish.yml
Labels: github_actions, patch

#362 fix: add git config user.name and git config user.email
  .github/workflows/publish.yml
Labels: github_actions, patch

#363 fix: set YARN_ENABLE_IMMUTABLE_INSTALLS in yarn install after setting…
  .github/workflows/publish.yml
Labels: github_actions, patch

#364 fix: set YARN_CHECKSUM_BEHAVIOR for yarn.lock update
  .github/workflows/publish.yml
Labels: github_actions, patch

#365 fix: needs YARN_ENABLE_IMMUTABLE_INSTALLS
  .github/workflows/publish.yml
Labels: github_actions, patch

#367 fix: remove deplicate misc/postpublish.sh process
  .github/workflows/publish.yml
Labels: github_actions, patch

#371 chore(react): remove dropdown selector border
  packages/react/src/components/DropdownSelector/index.tsx
Labels: patch

#370 chore(react): fix wrong text color
  packages/react/src/components/FieldLabel/index.tsx
Labels: patch

#350 @charcoal-ui/theme の docs 作成
  docs/src/components/NavList.tsx
  docs/src/pages/@charcoal-ui/theme/colors.page.tsx
  docs/src/pages/@charcoal-ui/theme/quickstart.page.tsx
Labels: patch

#351 @charcoal-ui/foundation の docs 作成
  docs/package.json
  docs/src/components/NavList.tsx
  docs/src/pages/@charcoal-ui/foundation/borderRadius.page.tsx
  docs/src/pages/@charcoal-ui/foundation/breakPoint.page.tsx
  docs/src/pages/@charcoal-ui/foundation/color.page.tsx
  docs/src/pages/@charcoal-ui/foundation/effect.page.tsx
  docs/src/pages/@charcoal-ui/foundation/grid.page.tsx
  docs/src/pages/@charcoal-ui/foundation/quickstart.page.tsx
  docs/src/pages/@charcoal-ui/foundation/spacing.page.tsx
  docs/src/pages/@charcoal-ui/foundation/typography.page.tsx
  docs/yarn.lock
Labels: minor

#368 publishのworkflowを修正
  .github/workflows/publish.yml
  lerna.json
  misc/postpublish.sh
  package.json
  packages/foundation/package.json
  packages/icon-files/package.json
  packages/icons-cli/package.json
  packages/icons/package.json
  packages/react-sandbox/package.json
  packages/react/package.json
  packages/styled/package.json
  packages/tailwind-config/package.json
  packages/tailwind-diff/package.json
  packages/theme/package.json
  packages/utils/package.json
  yarn.lock
Labels: github_actions, patch

#372 Checkboxのパフォーマンステスト
  .github/workflows/test.yml
  packages/react/jest.config.mjs
  packages/react/src/components/Checkbox/performance.test.tsx
Labels: patch
