Repository pixiv/charcoal, pull requests merged in 2024-05, with the labels that each got.

#513 feat: allow type radio group value
  packages/react/src/components/Radio/index.story.tsx
  packages/react/src/components/Radio/index.tsx
Labels: minor

#530 add sideEffects: true to style-loader
  .storybook/main.js
Labels: major, image snapshots update

#531 Update the styles of the readonly Checkbox
  packages/react/src/components/Checkbox/__snapshots__/index.story.storyshot
  packages/react/src/components/Checkbox/index.story.tsx
  packages/react/src/components/Checkbox/index.tsx
Labels: patch, image snapshots update

#519 feat: update the Checkbox v4
  docs/src/pages/@charcoal-ui/react/Checkbox/apiData.tsx
  docs/yarn.lock
  packages/react/src/components/Checkbox/CheckboxInput/__snapshots__/index.story.storyshot
  packages/react/src/components/Checkbox/CheckboxInput/index.css
  packages/react/src/components/Checkbox/CheckboxInput/index.story.tsx
  packages/react/src/components/Checkbox/CheckboxInput/index.tsx
  packages/react/src/components/Checkbox/CheckboxWithLabel.tsx
  packages/react/src/components/Checkbox/__snapshots__/index.story.storyshot
  packages/react/src/components/Checkbox/index.css
  packages/react/src/components/Checkbox/index.story.tsx
  packages/react/src/components/Checkbox/index.tsx
  packages/react/src/components/CheckboxInput/__snapshots__/index.story.storyshot
  packages/react/src/components/CheckboxInput/index.css
  packages/react/src/components/CheckboxInput/index.tsx
Labels: major, image snapshots update

#528 chore(react): add "*.css" to sideEffects
  packages/react/package.json
Labels: major

#534 Feat: add docs for storybook
  .storybook/main.js
  .storybook/preview.js
  .storybook/src/README.mdx
  packages/styled/src/README.mdx
  packages/styled/src/__snapshots__/addThemeUtils.story.storyshot
  packages/styled/src/addThemeUtils.mdx
  packages/styled/src/addThemeUtils.story.tsx
  packages/styled/src/createTheme.mdx
  packages/styled/src/index.test.tsx
Labels: patch

#533 tag item bg base64
  packages/react/src/components/TagItem/__snapshots__/index.story.storyshot
  packages/react/src/components/TagItem/index.story.tsx
Labels: patch, image snapshots update

#536 chore: test-storybook prepare base branch diff
  .github/workflows/test-storybook.yml
Labels: patch

#532 tag item bg base64 v4
  packages/react/src/components/TagItem/__snapshots__/index.story.storyshot
  packages/react/src/components/TagItem/index.story.tsx
Labels: major, image snapshots update

#518 feat: update switch to v4
  docs/src/pages/@charcoal-ui/react/Switch/apiData.tsx
  docs/src/pages/@charcoal-ui/react/Switch/index.page.tsx
  docs/yarn.lock
  packages/react/src/components/DropdownSelector/ListItem/__snapshots__/index.story.storyshot
  packages/react/src/components/Switch/SwitchInput/index.css
  packages/react/src/components/Switch/SwitchInput/index.tsx
  packages/react/src/components/Switch/SwitchWithLabel.tsx
  packages/react/src/components/Switch/__snapshots__/index.story.storyshot
  packages/react/src/components/Switch/index.css
  packages/react/src/components/Switch/index.story.tsx
  packages/react/src/components/Switch/index.tsx
Labels: major

#524 feat(react): update-segmented-control-v4
  packages/react/src/components/SegmentedControl/__snapshots__/index.story.storyshot
  packages/react/src/components/SegmentedControl/index.css
  packages/react/src/components/SegmentedControl/index.tsx
Labels: major

#526 feat(react): update clickable v4
  docs/src/pages/@charcoal-ui/react/IconButton/apiData.tsx
  docs/src/pages/@charcoal-ui/react/IconButton/sections.tsx
  packages/react/src/components/Clickable/__snapshots__/index.story.storyshot
  packages/react/src/components/Clickable/index.css
  packages/react/src/components/Clickable/index.story.tsx
  packages/react/src/components/Clickable/index.tsx
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/IconButton/__snapshots__/index.story.storyshot
  packages/react/src/components/IconButton/index.tsx
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
  packages/react/src/components/TextArea/__snapshots__/TextArea.story.storyshot
  packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot
  packages/react/src/index.ts
Labels: major

#529 chore(tailwind-config): wrap unstyled component
  packages/tailwind-config/src/docs/borderRadius/index.mdx
  packages/tailwind-config/src/docs/colors/index.mdx
  packages/tailwind-config/src/docs/gradient/index.mdx
  packages/tailwind-config/src/docs/screens/index.mdx
  packages/tailwind-config/src/docs/spacing/index.mdx
  packages/tailwind-config/src/docs/typography/index.mdx
Labels: patch

#540 test: update stories order
  .storybook/preview.js
  .storybook/src/README.mdx
  packages/react/src/components/Button/__snapshots__/index.story.storyshot
  packages/react/src/components/Button/index.story.tsx
  packages/react/src/components/Checkbox/__snapshots__/index.story.storyshot
  packages/react/src/components/Checkbox/index.story.tsx
  packages/react/src/components/Clickable/__snapshots__/index.story.storyshot
  packages/react/src/components/Clickable/index.story.tsx
  packages/react/src/components/DropdownSelector/ListItem/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/ListItem/index.story.tsx
  packages/react/src/components/DropdownSelector/MenuList/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/MenuList/index.story.tsx
  packages/react/src/components/DropdownSelector/Popover/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/Popover/index.story.tsx
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/index.story.tsx
  packages/react/src/components/Icon/__snapshots__/index.story.storyshot
  packages/react/src/components/Icon/index.story.tsx
  packages/react/src/components/IconButton/__snapshots__/index.story.storyshot
  packages/react/src/components/IconButton/index.story.tsx
  packages/react/src/components/LoadingSpinner/__snapshots__/index.story.storyshot
  packages/react/src/components/LoadingSpinner/index.story.tsx
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
  packages/react/src/components/Modal/index.story.tsx
  packages/react/src/components/MultiSelect/__snapshots__/index.story.storyshot
  packages/react/src/components/MultiSelect/index.story.tsx
  packages/react/src/components/Radio/__snapshots__/index.story.storyshot
  packages/react/src/components/Radio/index.story.tsx
  packages/react/src/components/SegmentedControl/__snapshots__/index.story.storyshot
  packages/react/src/components/SegmentedControl/index.story.tsx
  packages/react/src/components/Switch/__snapshots__/index.story.storyshot
  packages/react/src/components/Switch/index.story.tsx
  packages/react/src/components/TagItem/__snapshots__/index.story.storyshot
  packages/react/src/components/TagItem/index.story.tsx
  packages/react/src/components/TextArea/TextArea.story.tsx
  packages/react/src/components/TextArea/__snapshots__/TextArea.story.storyshot
  packages/react/src/components/TextField/TextField.story.tsx
  packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot
Labels: patch, image snapshots update

#522 feat(react): update radio v4
  docs/src/pages/@charcoal-ui/react/Radio/ExampleRadio.tsx
  docs/src/pages/@charcoal-ui/react/Radio/apiData.tsx
  docs/src/pages/@charcoal-ui/react/Radio/index.page.tsx
  docs/src/pages/@charcoal-ui/react/Radio/sections.tsx
  packages/react/src/components/Radio/__snapshots__/index.story.storyshot
  packages/react/src/components/Radio/index.css
  packages/react/src/components/Radio/index.story.tsx
  packages/react/src/components/Radio/index.test.tsx
  packages/react/src/components/Radio/index.tsx
Labels: major, image snapshots update

#523 feat(react): update loading spinner v4
  packages/react/src/components/LoadingSpinner/__snapshots__/LoadingSpinnerIcon.story.storyshot
  packages/react/src/components/LoadingSpinner/__snapshots__/index.story.storyshot
  packages/react/src/components/LoadingSpinner/index.css
  packages/react/src/components/LoadingSpinner/index.tsx
  packages/react/src/type.d.ts
Labels: major, image snapshots update

#539 feat: update FieldLabel v4
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/index.tsx
  packages/react/src/components/FieldLabel/index.css
  packages/react/src/components/FieldLabel/index.tsx
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
  packages/react/src/components/TextArea/__snapshots__/TextArea.story.storyshot
  packages/react/src/components/TextArea/index.tsx
  packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot
  packages/react/src/components/TextField/index.tsx
Labels: major, image snapshots update

#538 feat: update Modal v4
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/Modal/Dialog/index.css
  packages/react/src/components/Modal/Dialog/index.tsx
  packages/react/src/components/Modal/ModalPlumbing.css
  packages/react/src/components/Modal/ModalPlumbing.tsx
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
  packages/react/src/components/Modal/index.css
  packages/react/src/components/Modal/index.tsx
Labels: major

#516 feat(react): update tag item v4
  docs/src/pages/@charcoal-ui/react/TagItem/apiData.tsx
  packages/react/src/_lib/useClassNames.ts
  packages/react/src/components/TagItem/__snapshots__/index.story.storyshot
  packages/react/src/components/TagItem/index.css
  packages/react/src/components/TagItem/index.tsx
  packages/react/src/type.d.ts
Labels: major, image snapshots update

#525 feat(react): update icon button v4
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/IconButton/__snapshots__/index.story.storyshot
  packages/react/src/components/IconButton/index.css
  packages/react/src/components/IconButton/index.story.tsx
  packages/react/src/components/IconButton/index.tsx
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
Labels: major

#537 feat: update TextField and TextArea API
  docs/src/pages/@charcoal-ui/react/TextArea/apiData.tsx
  docs/src/pages/@charcoal-ui/react/TextField/apiData.tsx
  docs/yarn.lock
  packages/react/package.json
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
  packages/react/src/components/TextArea/__snapshots__/TextArea.story.storyshot
  packages/react/src/components/TextArea/index.tsx
  packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot
  packages/react/src/components/TextField/index.tsx
  yarn.lock
Labels: major
