Repository pixiv/charcoal, pull requests merged in 2024-03, with the labels that each got.

#470 docs: fix switch layout
  docs/src/pages/@charcoal-ui/react/Switch/index.page.tsx
Labels: patch

#472 Fix: The modal closed when clicking the scrollbar on the modal background.
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
  packages/react/src/components/Modal/index.tsx
  packages/react/src/components/Modal/useCustomModalOverlay.tsx
Labels: patch

#471 Fix: Input props are not passed to the `<input />`
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
  packages/react/src/components/TextArea/index.tsx
  packages/react/src/components/TextField/TextField.story.tsx
  packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot
  packages/react/src/components/TextField/index.tsx
Labels: patch

#473 Fix: Modal does not prevent body scrolling.
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
  packages/react/src/components/Modal/index.story.tsx
  packages/react/src/components/Modal/useCustomModalOverlay.tsx
Labels: patch

#475 Configured test-runner for image snapshot testing
  .github/workflows/test.yml
  .gitignore
  .storybook/test-runner.ts
  package.json
  yarn.lock
Labels: patch

#474 Feat: add theme utils
  .storybook/global.css
  docs/src/components/NavList.tsx
  docs/src/pages/@charcoal-ui/styled/Colors/index.page.tsx
  docs/src/pages/@charcoal-ui/styled/bg/Preview.tsx
  docs/src/pages/@charcoal-ui/styled/bg/index.page.tsx
  docs/src/pages/@charcoal-ui/styled/border/Preview.tsx
  docs/src/pages/@charcoal-ui/styled/border/index.page.tsx
  docs/src/pages/@charcoal-ui/styled/borderRadius/Preview.tsx
  docs/src/pages/@charcoal-ui/styled/borderRadius/index.page.tsx
  docs/src/pages/@charcoal-ui/styled/disabled/Preview.tsx
  docs/src/pages/@charcoal-ui/styled/disabled/index.page.tsx
  docs/src/pages/@charcoal-ui/styled/font/Preview.tsx
  docs/src/pages/@charcoal-ui/styled/font/index.page.tsx
  docs/src/pages/@charcoal-ui/styled/height/Preview.tsx
  docs/src/pages/@charcoal-ui/styled/height/index.page.tsx
  docs/src/pages/@charcoal-ui/styled/margin/Preview.tsx
  docs/src/pages/@charcoal-ui/styled/margin/index.page.tsx
  docs/src/pages/@charcoal-ui/styled/outline/Preview.tsx
  docs/src/pages/@charcoal-ui/styled/outline/index.page.tsx
  docs/src/pages/@charcoal-ui/styled/padding/Preview.tsx
  docs/src/pages/@charcoal-ui/styled/padding/index.page.tsx
  docs/src/pages/@charcoal-ui/styled/quickstart.page.tsx
  docs/src/pages/@charcoal-ui/styled/typography/Preview.tsx
  docs/src/pages/@charcoal-ui/styled/typography/index.page.tsx
  docs/src/pages/@charcoal-ui/styled/width/Preview.tsx
  docs/src/pages/@charcoal-ui/styled/width/index.page.tsx
  docs/yarn.lock
  packages/styled/src/__snapshots__/index.story.storyshot
  packages/styled/src/__snapshots__/index.test.tsx.snap
  packages/styled/src/index.story.tsx
  packages/styled/src/index.test.tsx
  packages/styled/src/index.ts
  packages/styled/src/storyHelper.ts
  packages/styled/src/styles/assertiveRingCss.ts
  packages/styled/src/styles/disabledCss.ts
  packages/styled/src/themeUtils.mdx
  packages/styled/src/utils/CharcoalStyledTheme.ts
  packages/styled/src/utils/addThemeUtils.ts
  packages/styled/src/utils/gap.ts
  packages/styled/src/utils/helpers/SpacingType.ts
  packages/styled/src/utils/helpers/pxIfNum.ts
  packages/styled/src/utils/margin.ts
  packages/styled/src/utils/padding.ts
  packages/styled/src/utils/typographyCss.ts
Labels: minor

#469 feat: update button to CSS-based implementation
  .github/workflows/bundle-size.yml
  .github/workflows/docs-hosting-pr.yml
  .github/workflows/test.yml
  docs/src/pages/@charcoal-ui/react/Button/apiData.tsx
  docs/src/pages/_app.page.tsx
  docs/yarn.lock
  jest.config.mjs
  package.json
  packages/react/package.json
  packages/react/postcss.config.js
  packages/react/src/_lib/useClassNames.ts
  packages/react/src/components/Button/StyledButton.tsx
  packages/react/src/components/Button/__snapshots__/index.story.storyshot
  packages/react/src/components/Button/index.css
  packages/react/src/components/Button/index.story.tsx
  packages/react/src/components/Button/index.tsx
  packages/react/src/components/Button/lib/variantToBackground.tsx
  packages/react/src/components/Button/lib/variantToFont.tsx
  packages/react/src/components/DropdownSelector/Popover/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
  yarn.lock
Labels: major

#483 CI: Added the storybook preview in PR.
  .github/workflows/docs-hosting-pr.yml
  .gitignore
  docs/src/components/NavList.tsx
  packages/styled/src/__snapshots__/index.story.storyshot
  packages/styled/src/__snapshots__/index.test.tsx.snap
  packages/styled/src/index.story.tsx
Labels: patch

#461 Hello image snapshots
  .dockerignore
  .github/workflows/test-storybook.yml
  .gitignore
  .storybook/global.css
  .storybook/preview-head.html
  package.json
  packages/react/src/components/LoadingSpinner/LoadingSpinnerIcon.story.tsx
  packages/react/src/components/LoadingSpinner/index.story.tsx
  yarn.lock
Labels: patch, image snapshots update

#480 Fix: disabled items can be selected using the keyboard.
  packages/react/src/components/DropdownSelector/MenuItem/internals/useMenuItemHandleKeyDown.tsx
  packages/react/src/components/DropdownSelector/MenuList/MenuListContext.ts
  packages/react/src/components/DropdownSelector/MenuList/index.tsx
  packages/react/src/components/DropdownSelector/MenuList/internals/getValuesRecursive.tsx
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/index.story.tsx
Labels: bug, patch

#484 Test: Changed the story title of the `styled/example`.
  packages/styled/src/__snapshots__/index.story.storyshot
  packages/styled/src/index.story.tsx
Labels: patch, image snapshots update

#481 Feat: Added hidden `<select />` to the `DropdownSelector`.
  docs/src/pages/@charcoal-ui/react/DropdownSelector/apiData.tsx
  docs/yarn.lock
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/index.story.tsx
  packages/react/src/components/DropdownSelector/index.tsx
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
Labels: minor, image snapshots update

#486 Change image snapshot test threshold, add waiting 200ms
  .storybook/test-runner.ts
Labels: patch

#487 Fix: Modified DropdownMenuItem styles.
  packages/react/src/components/DropdownSelector/ListItem/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/ListItem/index.tsx
  packages/react/src/components/DropdownSelector/MenuList/__snapshots__/index.story.storyshot
Labels: patch

#482 Add types field to exports of pakcage.json
  docs/package.json
  docs/yarn.lock
  packages/foundation/package.json
  packages/icons/package.json
  packages/react-sandbox/package.json
  packages/react/package.json
  packages/styled/package.json
  packages/tailwind-config/package.json
  packages/theme/package.json
Labels: patch

#488 Add release scripts dist-tag option
  .github/workflows/publish.yml
  lerna.json
  packages/esbuild-plugin-styled-components/package.json
  packages/foundation/package.json
  packages/icon-files/package.json
  packages/icons-cli/package.json
  packages/icons/package.json
  packages/react-sandbox/package.json
  packages/react/package.json
  packages/styled/package.json
  packages/tailwind-config/package.json
  packages/tailwind-diff/package.json
  packages/theme/package.json
  packages/utils/package.json
  yarn.lock
Labels: patch

#489 Fix: Resolved unexpected button width issue when `as="a"`.
  packages/react/src/components/Button/index.css
Labels: minor

#491 Fixed: Got an error log when using DropdownSelector.
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/index.tsx
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
Labels: patch

#476 chore(react): update button storybook
  packages/react/src/components/Button/__snapshots__/index.story.storyshot
  packages/react/src/components/Button/index.story.tsx
Labels: patch, image snapshots update

#492 Merge `v3.10.1` into `v4.0.0`
  packages/react/src/components/Button/__snapshots__/index.story.storyshot
  packages/react/src/components/Button/index.story.tsx
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/index.tsx
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
Labels: patch

#462 replace to csf3 PixivIcon story
  package.json
  packages/icons/src/PixivIcon.story.tsx
  yarn.lock
Labels: patch

#493 Feat: Added `componentAs` to the `Button`.
  docs/src/pages/@charcoal-ui/react/Button/apiData.tsx
  docs/yarn.lock
  packages/react/src/components/Button/__snapshots__/index.test.tsx.snap
  packages/react/src/components/Button/index.test.tsx
  packages/react/src/components/Button/index.tsx
Labels: minor

#495 Fix: input handling for software keyboard in modal dialogs
  packages/react/src/components/Modal/useCustomModalOverlay.tsx
Labels: patch

#496 chore/storybook-checkbox
  package.json
  packages/react/src/components/Checkbox/__snapshots__/index.story.storyshot
  packages/react/src/components/Checkbox/index.story.tsx
  packages/react/src/components/Checkbox/index.tsx
  yarn.lock
Labels: patch, image snapshots update

#494 Replace multiselect icon with icon component
  .storybook/test-runner.ts
  jest.setup.ts
  packages/react/src/components/MultiSelect/index.tsx
Labels: patch, image snapshots update
