Repository pixiv/charcoal, pull requests merged in 2024-11, with the labels that each got.

#651 fix: pass down className prop
  packages/react/src/components/TextField/index.tsx
Labels: major

#653 fix: update ci config
  .github/workflows/bundle-size.yml
  .github/workflows/docs-hosting-pr.yml
  .github/workflows/test-storybook.yml
  .github/workflows/test.yml
Labels: patch

#652 fix: update design token usage
  .github/workflows/bundle-size.yml
  .github/workflows/docs-hosting-pr.yml
  .github/workflows/test-storybook.yml
  .github/workflows/test.yml
  packages/react/src/components/Button/index.css
  packages/react/src/components/Checkbox/CheckboxInput/index.css
  packages/react/src/components/Checkbox/index.css
  packages/react/src/components/Clickable/__snapshots__/index.story.storyshot
  packages/react/src/components/Clickable/index.story.tsx
  packages/react/src/components/DropdownSelector/ListItem/index.css
  packages/react/src/components/DropdownSelector/Popover/index.css
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/index.css
  packages/react/src/components/DropdownSelector/index.story.tsx
  packages/react/src/components/IconButton/__snapshots__/index.story.storyshot
  packages/react/src/components/IconButton/index.css
  packages/react/src/components/IconButton/index.story.tsx
  packages/react/src/components/LoadingSpinner/index.css
  packages/react/src/components/Modal/ModalPlumbing.css
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
  packages/react/src/components/Modal/index.story.tsx
  packages/react/src/components/Radio/RadioInput/index.css
  packages/react/src/components/Radio/__snapshots__/index.story.storyshot
  packages/react/src/components/Radio/index.css
  packages/react/src/components/Radio/index.story.tsx
  packages/react/src/components/SegmentedControl/index.css
  packages/react/src/components/Switch/SwitchInput/index.css
  packages/react/src/components/Switch/index.css
  packages/react/src/components/TagItem/index.css
  packages/react/src/components/TextArea/index.css
  packages/react/src/components/TextField/AssistiveText/index.css
  packages/react/src/components/TextField/index.css
Labels: major, image snapshots update
