Repository pixiv/charcoal, pull requests merged in 2024-06, with the labels that each got.

#550 feat: add modal button aria label and export ModalCloseButton
  packages/react/src/components/IconButton/__snapshots__/index.story.storyshot
  packages/react/src/components/IconButton/index.tsx
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
  packages/react/src/components/Modal/index.tsx
  packages/react/src/index.ts
Labels: minor

#551 Fix for closeButtonAriaLabel in Modal docs
  docs/src/pages/@charcoal-ui/react/Modal/apiData.tsx
  docs/yarn.lock
Labels: patch

#552 fix: avoid SSRProvider after react 18
  docs/src/pages/@charcoal-ui/react/ssr.page.tsx
  docs/yarn.lock
  packages/react/README.md
  packages/react/src/core/SSRProvider.tsx
Labels: patch

#543 feat: add the rounded style to the Checkbox
  docs/src/components/NavList.tsx
  docs/src/pages/@charcoal-ui/react/Checkbox/apiData.tsx
  docs/src/pages/@charcoal-ui/react/MultiSelect/ExampleMultiSelect.tsx
  docs/src/pages/@charcoal-ui/react/MultiSelect/apiData.tsx
  docs/src/pages/@charcoal-ui/react/MultiSelect/index.page.tsx
  docs/src/pages/@charcoal-ui/react/MultiSelect/sections.tsx
  docs/yarn.lock
  packages/react/src/components/Checkbox/CheckboxInput/__snapshots__/index.story.storyshot
  packages/react/src/components/Checkbox/CheckboxInput/index.css
  packages/react/src/components/Checkbox/CheckboxInput/index.story.tsx
  packages/react/src/components/Checkbox/CheckboxInput/index.tsx
  packages/react/src/components/MultiSelect/__snapshots__/index.story.storyshot
  packages/react/src/components/MultiSelect/context.ts
  packages/react/src/components/MultiSelect/index.story.tsx
  packages/react/src/components/MultiSelect/index.test.tsx
  packages/react/src/components/MultiSelect/index.tsx
  packages/react/src/index.ts
Labels: major, image snapshots update

#557 fix: pixiv-icon waitUntilVisible condition
  packages/icons/src/PixivIcon.ts
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
  packages/react/src/components/Modal/index.story.tsx
Labels: patch, image snapshots update

#556 chore(theme): migrate docs
  packages/theme/src/docs/Color.mdx
  packages/theme/src/docs/README.mdx
  packages/theme/src/docs/ThemeColors.tsx
Labels: patch

#502 Add tokne-cli for generating design token from Figma variables
  .github/workflows/tokens.yml
  docs/yarn.lock
  packages/token-cli/.gitignore
  packages/token-cli/README.md
  packages/token-cli/package.json
  packages/token-cli/pixiv-dark.config.js
  packages/token-cli/pixiv-light.config.js
  packages/token-cli/src/createToken.ts
  packages/token-cli/src/figma/index.ts
  packages/token-cli/src/index.ts
  packages/token-cli/src/types.d.ts
  packages/token-cli/src/utils.ts
  packages/token-cli/src/utils/color.ts
  packages/token-cli/tsconfig.build.json
  packages/token-cli/tsconfig.json
  packages/token-cli/tsup.config.ts
  yarn.lock
Labels: patch

#542 feat(icons): convert readme icons
  packages/icons/src/CustomIcon.mdx
  packages/icons/src/README.mdx
  packages/icons/src/SSR.mdx
Labels: patch

#544 chore(styled): update storybook guide
  packages/styled/src/README.mdx
Labels: patch

#547 feat: textfield change to styled to css
  packages/react/src/_lib/createDivComponent.tsx
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/index.tsx
  packages/react/src/components/Modal/ModalPlumbing.tsx
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
  packages/react/src/components/TextArea/__snapshots__/TextArea.story.storyshot
  packages/react/src/components/TextArea/index.tsx
  packages/react/src/components/TextField/AssistiveText/index.css
  packages/react/src/components/TextField/AssistiveText/index.tsx
  packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot
  packages/react/src/components/TextField/index.css
  packages/react/src/components/TextField/index.tsx
Labels: major

#546 chore(tailwind-config): update storybook guide
  packages/tailwind-config/src/Custom.mdx
  packages/tailwind-config/src/README.mdx
Labels: patch

#554 chore(tailwind-diff): migrate docs
  packages/tailwind-diff/src/Check.mdx
  packages/tailwind-diff/src/Dump.mdx
  packages/tailwind-diff/src/REAMDE.mdx
Labels: patch

#555 chore(foundation): migrate docs
  packages/foundation/src/README.mdx
Labels: patch

#548 feat: textarea change styled to css
  packages/react/src/components/TextArea/__snapshots__/TextArea.story.storyshot
  packages/react/src/components/TextArea/index.css
  packages/react/src/components/TextArea/index.tsx
Labels: major

#560 feat: textarea change styled to css
  packages/react/src/components/TextArea/__snapshots__/TextArea.story.storyshot
  packages/react/src/components/TextArea/index.css
  packages/react/src/components/TextArea/index.tsx
Labels: major

#559 feat: update RadioGroup
  docs/src/pages/@charcoal-ui/react/Radio/ExampleRadio.tsx
  docs/src/pages/@charcoal-ui/react/Radio/apiData.tsx
  docs/src/pages/@charcoal-ui/react/Radio/sections.tsx
  docs/yarn.lock
  packages/react/src/components/Radio/RadioGroup/index.css
  packages/react/src/components/Radio/RadioGroup/index.tsx
  packages/react/src/components/Radio/RadioGroupContext.ts
  packages/react/src/components/Radio/RadioInput/index.css
  packages/react/src/components/Radio/RadioInput/index.tsx
  packages/react/src/components/Radio/__snapshots__/index.story.storyshot
  packages/react/src/components/Radio/index.css
  packages/react/src/components/Radio/index.story.tsx
  packages/react/src/components/Radio/index.test.tsx
  packages/react/src/components/Radio/index.tsx
  packages/react/src/index.ts
Labels: major, image snapshots update

#549 feat: dropdown selector v4 styled to css
  packages/react/src/components/DropdownSelector/Divider.tsx
  packages/react/src/components/DropdownSelector/Divider/index.css
  packages/react/src/components/DropdownSelector/Divider/index.tsx
  packages/react/src/components/DropdownSelector/DropdownMenuItem.tsx
  packages/react/src/components/DropdownSelector/DropdownMenuItem/index.css
  packages/react/src/components/DropdownSelector/DropdownMenuItem/index.tsx
  packages/react/src/components/DropdownSelector/DropdownPopover.tsx
  packages/react/src/components/DropdownSelector/ListItem/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/ListItem/index.css
  packages/react/src/components/DropdownSelector/ListItem/index.tsx
  packages/react/src/components/DropdownSelector/MenuItem/index.tsx
  packages/react/src/components/DropdownSelector/MenuItem/internals/useMenuItemHandleKeyDown.tsx
  packages/react/src/components/DropdownSelector/MenuItemGroup/index.css
  packages/react/src/components/DropdownSelector/MenuItemGroup/index.tsx
  packages/react/src/components/DropdownSelector/MenuList/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/MenuList/index.css
  packages/react/src/components/DropdownSelector/MenuList/index.tsx
  packages/react/src/components/DropdownSelector/Popover/index.css
  packages/react/src/components/DropdownSelector/Popover/index.tsx
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/index.css
  packages/react/src/components/DropdownSelector/index.story.tsx
  packages/react/src/components/DropdownSelector/index.tsx
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
Labels: major, image snapshots update

#562 chore: reorder docs story
  .storybook/preview.js
  packages/icons/src/CustomIcon.mdx
  packages/tailwind-config/src/README.mdx
Labels: patch

#563 feat(theme): add CSS and json for v4
  .prettierignore
  packages/theme/.prettierignore
  packages/theme/package.json
  packages/theme/src/css/_variables_dark.css
  packages/theme/src/css/_variables_light.css
  packages/theme/src/json/base.json
  packages/theme/src/json/pixiv-dark.json
  packages/theme/src/json/pixiv-light.json
  packages/token-cli/jest.config.mjs
  yarn.lock
Labels: patch

#569 packages install jest babel
  .github/workflows/test.yml
  .storybook/babel.config.js
  package.json
  packages/foundation/babel.config.js
  packages/foundation/package.json
  packages/icons/babel.config.js
  packages/icons/package.json
  packages/react-sandbox/babel.config.js
  packages/react-sandbox/package.json
  packages/react/babel.config.js
  packages/react/package.json
  packages/react/src/components/Checkbox/CheckboxInput/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/ListItem/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/Popover/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/LoadingSpinner/__snapshots__/index.story.storyshot
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
  packages/react/src/components/Radio/__snapshots__/index.story.storyshot
  packages/react/src/components/TagItem/__snapshots__/index.story.storyshot
  packages/react/src/components/TextArea/__snapshots__/TextArea.story.storyshot
  packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot
  packages/styled/babel.config.js
  packages/styled/package.json
  packages/tailwind-config/babel.config.js
  packages/tailwind-config/package.json
  packages/tailwind-config/src/__snapshots__/index.test.ts.snap
  packages/theme/babel.config.js
  packages/theme/package.json
  packages/utils/babel.config.js
  packages/utils/package.json
  yarn.lock
Labels: patch

#565 feat: remove styled from react
  .github/workflows/test.yml
  .storybook/babel.config.js
  .storybook/test-runner.ts
  docs/src/pages/@charcoal-ui/react/CharcoalProviderExample.tsx
  docs/src/pages/@charcoal-ui/react/Modal/ExampleModal.tsx
  docs/src/pages/@charcoal-ui/react/Modal/index.page.tsx
  docs/src/pages/@charcoal-ui/react/Modal/useIsSSR.ts
  docs/yarn.lock
  package.json
  packages/foundation/babel.config.js
  packages/foundation/package.json
  packages/icons/babel.config.js
  packages/icons/package.json
  packages/react-sandbox/babel.config.js
  packages/react-sandbox/package.json
  packages/react/babel.config.js
  packages/react/package.json
  packages/react/src/_lib/compat.ts
  packages/react/src/components/Button/index.test.tsx
  packages/react/src/components/Checkbox/CheckboxInput/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/ListItem/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/ListItem/index.story.tsx
  packages/react/src/components/DropdownSelector/Popover/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/LoadingSpinner/__snapshots__/index.story.storyshot
  packages/react/src/components/Modal/Dialog/index.tsx
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
  packages/react/src/components/Modal/__stories__/InternalScrollStory.tsx
  packages/react/src/components/Modal/index.story.tsx
  packages/react/src/components/Modal/index.tsx
  packages/react/src/components/Modal/useCustomModalOverlay.tsx
  packages/react/src/components/Radio/__snapshots__/index.story.storyshot
  packages/react/src/components/Radio/index.story.tsx
  packages/react/src/components/Radio/index.test.tsx
  packages/react/src/components/TagItem/__snapshots__/index.story.storyshot
  packages/react/src/components/TextArea/__snapshots__/TextArea.story.storyshot
  packages/react/src/components/TextField/TextField.story.tsx
  packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot
  packages/react/src/components/a11y.test.tsx
  packages/react/src/core/CharcoalProvider.tsx
  packages/react/src/styled.ts
  packages/react/src/type.d.ts
  packages/styled/babel.config.js
  packages/styled/package.json
  packages/tailwind-config/babel.config.js
  packages/tailwind-config/package.json
  packages/tailwind-config/src/__snapshots__/index.test.ts.snap
  packages/theme/babel.config.js
  packages/theme/package.json
  packages/utils/babel.config.js
  packages/utils/package.json
  yarn.lock
Labels: major

#566 Add design token updating workflow
  .github/workflows/tokens.yml
  .prettierignore
  package.json
  packages/pullrequest-cli/README.md
  packages/pullrequest-cli/package.json
  packages/pullrequest-cli/src/GitHubClient.ts
  packages/pullrequest-cli/src/getChangedFiles.ts
  packages/pullrequest-cli/src/index.ts
  packages/pullrequest-cli/src/utils.ts
  packages/pullrequest-cli/tsconfig.build.json
  packages/pullrequest-cli/tsconfig.json
  packages/pullrequest-cli/tsup.config.ts
  yarn.lock
Labels: patch

#572 fix VRT CI
  .github/workflows/test-storybook.yml
Labels: patch
