Repository pixiv/charcoal, pull requests merged in 2024-12, with the labels that each got.

#660 tokenが参照できない時、warnを出して処理を続けるようにする
  packages/token-cli/src/createToken.ts
  packages/token-cli/src/figma/index.ts
Labels: patch

#662 (v4) tokenが参照できない時、warnを出して処理を続けるようにする
  packages/token-cli/src/createToken.ts
  packages/token-cli/src/figma/index.ts
Labels: major

#667 fix: keep dts and fix copy target path when update theme
  .github/workflows/tokens.yml
  packages/pullrequest-cli/src/getChangedFiles.ts
Labels: patch

#657 chore(token-cli): figma から得られる float に suffix px を付ける
  packages/theme/src/css/_variables_dark.css
  packages/theme/src/css/_variables_light.css
  packages/theme/src/json/base.json
  packages/theme/src/json/pixiv-dark.json
  packages/theme/src/json/pixiv-light.json
  packages/theme/src/token-object/__snapshots__/token-object.test.ts.snap
  packages/theme/src/token-object/helpers/__snapshots__/changecase-keys.test.ts.snap
  packages/token-cli/src/figma/index.ts
Labels: major

#655 feat: token v2 demo styled
  .storybook/theme-decorator.tsx
  packages/react/docs/__snapshots__/token-v2-demo-styled.story.storyshot
  packages/react/docs/token-v2-demo-styled.story.tsx
  packages/react/tsconfig.json
  tsconfig.base.json
Labels: minor, image snapshots update

#673 feat: add token v2 demo bench
  packages/react/docs/TokenV2Demo.bench.tsx
Labels: patch, image snapshots update

#674 feat: mark tokens unstable
  .prettierignore
  .storybook/theme-decorator.tsx
  packages/react/docs/TokenV2DemoStyled.tsx
  packages/tailwind-config/src/tokenV2.ts
  packages/theme/cli/token-object.ts
  packages/theme/package.json
  packages/theme/src/unstable-css/_variables_dark.css
  packages/theme/src/unstable-css/_variables_dark.css.d.ts
  packages/theme/src/unstable-css/_variables_light.css
  packages/theme/src/unstable-css/_variables_light.css.d.ts
  packages/theme/src/unstable-token-object/__snapshots__/token-object.test.ts.snap
  packages/theme/src/unstable-token-object/helpers/__snapshots__/changecase-keys.test.ts.snap
  packages/theme/src/unstable-token-object/helpers/changecase-keys.test-d.ts
  packages/theme/src/unstable-token-object/helpers/changecase-keys.test.ts
  packages/theme/src/unstable-token-object/helpers/changecase-keys.ts
  packages/theme/src/unstable-token-object/helpers/is-empty-array.ts
  packages/theme/src/unstable-token-object/helpers/nest-object.test.ts
  packages/theme/src/unstable-token-object/helpers/nest-object.ts
  packages/theme/src/unstable-token-object/index.ts
  packages/theme/src/unstable-token-object/reference-token.test.ts
  packages/theme/src/unstable-token-object/reference-token.ts
  packages/theme/src/unstable-token-object/to-token-object.ts
  packages/theme/src/unstable-token-object/token-object.bench.ts
  packages/theme/src/unstable-token-object/token-object.test.ts
  packages/theme/src/unstable-token-object/types.ts
  packages/theme/tsup.config.ts
Labels: major, image snapshots update

#675 fix: revert remove multiSelect
  packages/react/src/components/MultiSelect/__snapshots__/index.story.storyshot
  packages/react/src/components/MultiSelect/context.ts
  packages/react/src/components/MultiSelect/index.css
  packages/react/src/components/MultiSelect/index.story.tsx
  packages/react/src/components/MultiSelect/index.test.tsx
  packages/react/src/components/MultiSelect/index.tsx
  packages/react/src/index.ts
Labels: major, image snapshots update

#677 v4 release note
  .github/workflows/publish.yml
  .prettierignore
  .storybook/src/v4.0.0.mdx
  lerna.json
  packages/esbuild-plugin-styled-components/package.json
  packages/foundation/package.json
  packages/icon-files/package.json
  packages/icons-cli/package.json
  packages/icons/package.json
  packages/react-sandbox/package.json
  packages/react/package.json
  packages/styled/package.json
  packages/tailwind-config/package.json
  packages/tailwind-diff/package.json
  packages/theme/package.json
  packages/token-cli/package.json
  packages/utils/package.json
  yarn.lock
Labels: major

#678 feat: enabling css variables v1 via tailwind
  .storybook/src/v4.0.0.mdx
  .storybook/tailwind.config.js
  packages/tailwind-config/src/__snapshots__/index.test.ts.snap
  packages/tailwind-config/src/_lib/TailwindBuild.ts
  packages/tailwind-config/src/colors/plugin.ts
  packages/tailwind-config/src/colors/pluginTokenV1.ts
  packages/tailwind-config/src/index.ts
Labels: major

#679 分割可能でない単語がHintTextに含まれていたときにあふれないようにする
  packages/react-sandbox/src/components/HintText/index.story.tsx
  packages/react-sandbox/src/components/HintText/index.tsx
Labels: patch, image snapshots update

#680 v3 backport: abcang/hint-text-overflow-wrap-break-word
  packages/react-sandbox/src/components/HintText/index.story.tsx
  packages/react-sandbox/src/components/HintText/index.tsx
Labels: patch, image snapshots update

#682 fix: restore ClickableElement type
  packages/react/src/components/Clickable/index.tsx
  packages/react/src/index.ts
Labels: patch

#683 Theme/token V2 demo の snapshot を更新
  .storybook/test-runner.ts
  packages/react/docs/TokenV2Demo.story.tsx
  packages/react/docs/__snapshots__/TokenV2Demo.story.storyshot
Labels: patch, image snapshots update
