Repository pixiv/charcoal, pull requests merged in 2024-01, with the labels that each got.

#436 remove styled from tag item
  packages/react/src/components/TagItem/__snapshots__/index.story.storyshot
  packages/react/src/components/TagItem/index.tsx
Labels: patch

#435 Feat/remove-charcoal-styled-from-switch
  packages/react/src/components/DropdownSelector/ListItem/__snapshots__/index.story.storyshot
  packages/react/src/components/Switch/__snapshots__/index.story.storyshot
  packages/react/src/components/Switch/index.tsx
Labels: patch

#421 feat/remove charcoal styled from dropdownselector
  jest.setup.ts
  packages/react/src/components/DropdownSelector/DropdownMenuItem.tsx
  packages/react/src/components/DropdownSelector/ListItem/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/ListItem/index.tsx
  packages/react/src/components/DropdownSelector/MenuItemGroup/index.tsx
  packages/react/src/components/DropdownSelector/MenuList/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/Popover/index.tsx
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/index.tsx
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
Labels: patch

#397 fix: sub-module import polished
  packages/theme/src/default.ts
  packages/utils/src/index.ts
Labels: patch

#390 fix: modal dismissable
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
  packages/react/src/components/Modal/index.story.tsx
  packages/react/src/components/Modal/index.tsx
Labels: minor

#437 docs: add bundle-analyzer
  docs/next.config.js
  docs/package.json
  docs/yarn.lock
Labels: documentation, patch

#427 tailwind-configのTypography docs追加
  docs/src/components/NavList.tsx
  docs/src/components/tailwind-config/typography/HalfLeading.tsx
  docs/src/components/tailwind-config/typography/Sizes.tsx
  docs/src/components/tailwind-config/typography/utils.ts
  docs/src/pages/@charcoal-ui/tailwind-config/typography.page.tsx
Labels: patch

#428 tailwind-configのspacing docs追加
  docs/src/components/NavList.tsx
  docs/src/components/tailwind-config/spacing/Spacing.tsx
  docs/src/pages/@charcoal-ui/tailwind-config/spacing.page.tsx
Labels: patch

#429 tailwind-configのbreak points (screen) docs追加
  docs/src/components/NavList.tsx
  docs/src/components/tailwind-config/screens/Screens.tsx
  docs/src/pages/@charcoal-ui/tailwind-config/screens.page.tsx
Labels: patch

#430 tailwind-configにcolors docs追加
  docs/src/components/NavList.tsx
  docs/src/components/tailwind-config/colors/Colors.tsx
  docs/src/components/tailwind-config/colors/Gradients.tsx
  docs/src/components/tailwind-config/colors/TextColors.tsx
  docs/src/components/tailwind-config/colors/gradients/utils.ts
  docs/src/pages/@charcoal-ui/tailwind-config/colors.page.tsx
Labels: patch

#434 /reactのStorybook CSF3化 clickable編
  packages/react/src/components/Clickable/index.story.tsx
Labels: patch

#432 /reactのStorybook CSF3化 checkbox編
  packages/react/src/components/Checkbox/__snapshots__/snapshot.test.tsx.snap
  packages/react/src/components/Checkbox/index.story.tsx
  packages/react/src/components/Checkbox/performance.test.tsx
  packages/react/src/components/Checkbox/snapshot.test.tsx
Labels: patch

#443 Feat/add-test-runner
  .github/workflows/test.yml
  .gitignore
  .storybook/test-runner.ts
  package.json
  playwright.config.ts
  yarn.lock
Labels: patch

#422 chore: update react-aria
  packages/react/package.json
  packages/react/src/_lib/compat.ts
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
  packages/react/src/components/SegmentedControl/RadioGroupContext.tsx
  packages/react/src/components/SegmentedControl/__snapshots__/index.story.storyshot
  packages/react/src/components/SegmentedControl/index.tsx
  packages/react/src/components/TextArea/__snapshots__/TextArea.story.storyshot
  packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot
  yarn.lock
Labels: minor

#444 refactor: split the file into smaller
  packages/react/src/components/Button/StyledButton.tsx
  packages/react/src/components/Button/index.tsx
  packages/react/src/components/Button/lib/variantToBackground.tsx
  packages/react/src/components/Button/lib/variantToFont.tsx
Labels: patch

#446 feat: add a hover style to DropdownSelector
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/index.tsx
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
Labels: minor

#447 feat: enable long text in DropdownSelector
  packages/react/src/components/DropdownSelector/DropdownMenuItem.tsx
  packages/react/src/components/DropdownSelector/__snapshots__/index.story.storyshot
  packages/react/src/components/DropdownSelector/index.story.tsx
  packages/react/src/components/DropdownSelector/index.tsx
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
Labels: minor

#448 test: Update the story for the Switch component.
  packages/react/src/components/Switch/__snapshots__/index.story.storyshot
  packages/react/src/components/Switch/index.story.tsx
Labels: patch

#449 test: Updated the stories for the Radio component.
  packages/react/src/components/Radio/__snapshots__/index.story.storyshot
  packages/react/src/components/Radio/index.story.tsx
Labels: patch

#433 /reactのStorybook CSF3化 button編
  packages/react/src/components/Button/__snapshots__/index.story.storyshot
  packages/react/src/components/Button/index.story.tsx
Labels: patch

#442 /reactのStorybook CSF3化 LoadingSpinner編
  packages/react/src/components/LoadingSpinner/LoadingSpinnerIcon.story.tsx
  packages/react/src/components/LoadingSpinner/index.story.tsx
  packages/react/src/components/LoadingSpinner/index.tsx
Labels: patch
