Repository pixiv/charcoal, pull requests merged in 2024-10, with the labels that each got.

#629 feat(token-cli): add new category token for v4
  .github/workflows/tokens.yml
Labels: major

#628 fix: rename use theme key and update type
  packages/styled/src/helper.ts
Labels: minor

#630 feat: export removeHalfLeadingCss for migration
  packages/styled/src/index.ts
  packages/styled/src/utils/typographyCss.ts
Labels: minor

#627 feat(token-cli): add new category token
  .github/workflows/tokens.yml
Labels: patch

#634 docs(tailwind-config): tailwind-config/README.mdのリンク切れを修正
  packages/tailwind-config/README.md
Labels: patch

#635 fix: bump dompurify
  packages/icons/package.json
  yarn.lock
Labels: patch

#637 feat(icon-workflow): Enable creation of PRs to the base branch
  .github/workflows/icons.yml
Labels: major

#393 Feat: skip dom purify for trusted content
  packages/icons/src/PixivIcon.ts
  packages/icons/src/loaders/CharcoalIconFilesLoader.ts
  packages/icons/src/loaders/CustomIconLoader.ts
  packages/icons/src/loaders/Loadable.ts
  packages/icons/src/loaders/index.ts
Labels: major

#639 token json を結合して color や数値をとれるトークンオブジェクトを作成する
  eslint.config.mjs
  package.json
  packages/theme/cli/token-object.ts
  packages/theme/package.json
  packages/theme/src/css/_variables_dark.css.d.ts
  packages/theme/src/css/_variables_light.css.d.ts
  packages/theme/src/token-object/__snapshots__/token-object.test.ts.snap
  packages/theme/src/token-object/helpers/__snapshots__/changecase-keys.test.ts.snap
  packages/theme/src/token-object/helpers/changecase-keys.test-d.ts
  packages/theme/src/token-object/helpers/changecase-keys.test.ts
  packages/theme/src/token-object/helpers/changecase-keys.ts
  packages/theme/src/token-object/helpers/is-empty-array.ts
  packages/theme/src/token-object/helpers/nest-object.test.ts
  packages/theme/src/token-object/helpers/nest-object.ts
  packages/theme/src/token-object/index.ts
  packages/theme/src/token-object/reference-token.test.ts
  packages/theme/src/token-object/reference-token.ts
  packages/theme/src/token-object/to-token-object.ts
  packages/theme/src/token-object/token-object.bench.ts
  packages/theme/src/token-object/token-object.test.ts
  packages/theme/src/token-object/types.ts
  packages/theme/tsconfig.build.json
  packages/theme/tsconfig.json
  packages/theme/tsup.config.ts
  packages/theme/vitest.config.ts
  yarn.lock
Labels: major

#643 fix!(@charcoal-ui/icons): remove dompurify from v4.
  packages/icons/package.json
  packages/icons/src/PixivIcon.ts
  packages/icons/src/loaders/CharcoalIconFilesLoader.ts
  packages/icons/src/loaders/CustomIconLoader.ts
  packages/icons/src/loaders/Loadable.ts
  packages/icons/src/loaders/index.ts
  yarn.lock
Labels: major

#648 chore(@charcoal-ui/tailwind-config): add test for defaultConfig
  packages/tailwind-config/src/__snapshots__/index.test.ts.snap
  packages/tailwind-config/src/index.test.ts
Labels: patch

#649 fix: unify css variables json
  packages/theme/cli/token-object.ts
Labels: major
