Repository pixiv/charcoal, pull requests merged in 2025-02, with the labels that each got.

#616 upgrade react 18
  .storybook/main.js
  package.json
  packages/icons/package.json
  packages/react-sandbox/package.json
  packages/react-sandbox/src/_lib/ComponentAbstraction.tsx
  packages/react-sandbox/src/components/Carousel/index.tsx
  packages/react-sandbox/src/components/Filter/index.tsx
  packages/react-sandbox/src/components/HintText/index.tsx
  packages/react-sandbox/src/components/Pager/index.tsx
  packages/react-sandbox/src/components/WithIcon/index.tsx
  packages/react-sandbox/src/type.d.ts
  packages/react/package.json
  packages/react/src/components/Switch/SwitchInput/index.tsx
  packages/react/src/components/TextField/__snapshots__/TextField.story.storyshot
  packages/react/src/components/TextField/index.tsx
  packages/styled/package.json
  packages/styled/src/TokenInjector.tsx
  packages/styled/src/__snapshots__/addThemeUtils.story.storyshot
  packages/styled/src/__snapshots__/index.test.tsx.snap
  packages/styled/src/styles/disabledCss.ts
  packages/tailwind-config/package.json
  packages/token-cli/package.json
  packages/utils/package.json
  yarn.lock
Labels: major, image snapshots update

#699 fix: update unsafe non guideline scale ssr guide
  packages/icons/src/SSR.mdx
Labels: patch

#698 feat: add fixes and guide for tailwind v4
  .storybook/src/v4.0.0.mdx
  .storybook/tailwind.config.js
  eslint.config.mjs
  packages/icon-files/package.json
  packages/icons/src/ssr.ts
  packages/react/docs/TokenV2DemoTailwind.tsx
  packages/react/docs/__snapshots__/TokenV2Demo.story.storyshot
  packages/tailwind-config/README.md
  packages/tailwind-config/package.json
  packages/tailwind-config/src/Custom.mdx
  packages/tailwind-config/src/README.mdx
  packages/tailwind-config/src/__snapshots__/index.test.ts.snap
  packages/tailwind-config/src/__snapshots__/tokenV2.test.ts.snap
  packages/tailwind-config/src/_lib/TailwindBuild.ts
  packages/tailwind-config/src/colors/plugin.ts
  packages/tailwind-config/src/colors/toTailwindConfig.ts
  packages/tailwind-config/src/docs/borderRadius/index.ts
  packages/tailwind-config/src/docs/colors/Colors.tsx
  packages/tailwind-config/src/gradient/plugin.ts
  packages/tailwind-config/src/index.test.ts
  packages/tailwind-config/src/index.ts
  packages/tailwind-config/src/tokenV2.test.ts
  packages/tailwind-config/src/tokenV2.ts
  packages/tailwind-config/src/typography/plugin.ts
  packages/tailwind-config/src/util.ts
  packages/tailwind-diff/src/commands/dump.ts
  packages/utils/package.json
  pages/pages/utilities/tailwind-config.md
  yarn.lock
Labels: minor, image snapshots update

#700 chore(react): fix text field prefix, suffix visible condition
  packages/react/src/components/TextField/index.tsx
  packages/react/src/components/TextField/text-field.test.tsx
Labels: patch

#702 yarn から pnpm に変更
  .github/workflows/bundle-size.yml
  .github/workflows/docs-hosting-main.yml
  .github/workflows/docs-hosting-pr.yml
  .github/workflows/gh-pages.yml
  .github/workflows/icons.yml
  .github/workflows/publish.yml
  .github/workflows/test-storybook.yml
  .github/workflows/test.yml
  .github/workflows/tokens.yml
  .husky/commit-msg
  .prettierignore
  .storybook/docs-container.tsx
  .storybook/theme-decorator.tsx
  .storybook/use-dark-mode.ts
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-sources.cjs
  .yarnrc.yml
  eslint.config.mjs
  lerna.json
  package.json
  packages/esbuild-plugin-styled-components/package.json
  packages/icons/package.json
  packages/icons/src/PixivIcon.story.tsx
  packages/react-sandbox/package.json
  packages/react/.mise.toml
  packages/react/package.json
  packages/react/src/components/IconButton/index.tsx
  packages/react/src/components/Modal/__snapshots__/index.story.storyshot
  packages/react/src/components/SegmentedControl/__snapshots__/index.story.storyshot
  packages/react/src/components/TagItem/index.tsx
  packages/react/tsconfig.json
  packages/react/vitest.config.ts
  packages/react/vitest.setup.ts
  packages/styled/package.json
  packages/tailwind-config/package.json
  packages/tailwind-diff/src/commands/dump.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  vitest.setup.ts
  yarn.lock
Labels: patch
